### ISSUE TITLE
java.lang.UnsupportedOperationException: empty.maxBy   

### ISSUE THREAD

**Issue by jaymansfield** [nebulasio/research#2]
alpha: Int = 2
beta: Double = 0.1
mu: Double = 0.01
lambda: Int = 2
topK: Int = 2
GND: String = ground
txFile: String = txs.txt
resultFile: String = nr.txt
originalTxs: org.apache.spark.rdd.RDD[((String, String), (Double, Long))] = MapPartitionsRDD[4] at map at <console>:37
compute: (originalTxs: org.apache.spark.rdd.RDD[((String, String), (Double, Long))], sc: org.apache.spark.SparkContext)Unit
java.lang.UnsupportedOperationException: empty.maxBy                            
  at scala.collection.TraversableOnce$class.maxBy(TraversableOnce.scala:236)
  at scala.collection.mutable.ArrayOps$ofRef.maxBy(ArrayOps.scala:186)
  at wgc$1(<console>:165)
  at compute(<console>:214)
  ... 73 elided

**Comment by jaymansfield** [comment]
I have tried a few different versions of spark and scala and always get that same error message.
